services:
  tts:
    container_name: F5-TTS
    build: .
    restart: unless-stopped
    ports:
      - 8083:7860
    command: ["--host", "0.0.0.0", "--port", "7860"]
    volumes:
      - ./src:src
    networks:
      - external_network
      - internal_network
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

networks:
  external_network:
  internal_network:
    internal: true
